---
apiVersion: db-operator.widemeadows.de/v1
kind: Database
metadata:
  name: test
spec:
  serverRef:
    name: postgres-test
  name: test
  create: true
  delete: true
  grants:
    - user: test
      database:
        grants:
          - ALL PRIVILEGES
      schema:
        name: public
        grants:
          - ALL PRIVILEGES
