---
apiVersion: db-operator.widemeadows.de/v1
kind: Database
metadata:
  name: test
spec:
  serverRef:
    name: postgres-test
  name: test
  comment: "A test database"
  readOnly: false
  create: true
  delete: true
  grants:
    - user: test
      database:
        grants:
          - ALL PRIVILEGES
      schema:
        name: public
        grants:
          - ALL PRIVILEGES
---
apiVersion: db-operator.widemeadows.de/v1
kind: Database
metadata:
  name: foo
spec:
  serverRef:
    name: postgres-test
  name: foo
  comment: "Another test database"
  readOnly: false
  create: true
  delete: true
  grants:
    - user: test
      database:
        grants:
          - ALL PRIVILEGES
      schema:
        name: public
        grants:
          - ALL PRIVILEGES
---
apiVersion: db-operator.widemeadows.de/v1
kind: Database
metadata:
  name: bar
  namespace: postgres
spec:
  serverRef:
    name: postgres-test
  name: bar
  comment: "Yet another test database"
  readOnly: false
  create: true
  delete: true
  grants:
    - user: test
      database:
        grants:
          - ALL PRIVILEGES
      schema:
        name: public
        grants:
          - ALL PRIVILEGES
---
apiVersion: db-operator.widemeadows.de/v1
kind: Database
metadata:
  name: postgres
  namespace: postgres
spec:
  serverRef:
    name: postgres-test
  name: postgres
  readOnly: true
  create: false
  delete: false
